#!/bin/bash
grep -s -A5000 "<body[^<]*>" $1 > output
cp output $1
echo "processing..."
# cat $1

sed -i 's/<h1[^<]*>/# /g' $1
sed -i 's/<h2[^<]*>/## /g' $1
sed -i 's/<h3[^<]*>/### /g' $1
sed -i 's/<h4[^<]*>/#### /g' $1
sed -i 's/<h5[^<]*>/##### /g' $1
sed -i 's/<h6[^<]*>/###### /g' $1

sed -i 's/<\/h1[^<]*>/\n/g' $1
sed -i 's/<\/h2[^<]*>/\n/g' $1
sed -i 's/<\/h3[^<]*>/\n/g' $1
sed -i 's/<\/h4[^<]*>/\n/g' $1
sed -i 's/<\/h5[^<]*>/\n/g' $1
sed -i 's/<\/h6[^<]*>/\n/g' $1

sed -i 's/<pre><code[^<]*>/``` c\n/g' $1
sed -i 's/<\/code[^<]*><\/pre>/```\n/g' $1

sed -i 's/<code[^<]*>/```/g' $1
sed -i 's/<\/code[^<]*>/```/g' $1

sed -i 's/<[^<]*>//g' $1
sed -i 's//\n/g' $1

grep . $1 > output
cp output $1
