#!/bin/bash

mv -f "C:/Users/Mamo/Downloads/*.md" "C:/Users/Mamo/Downloads/recbin"

# curl --silent $1 > new.html
# cd "C:/Users/Mamo/Downloads"
# cat $1 > new.html
# cd -
# ls "C:\\Users\\Mamo\\Downloads"
# cat "C:\\Users\\Mamo\\Downloads\\new.mhtml" > new.html
# grep -A50000 "<!DOCTYPE html>" new.html > pre.txt
# grep -B50000 "</html>" pre.txt > pro.txt
# code new.html

echo getting the header and adding the script src...
grep -B500 "<head>" new.html > pre.txt
cat scriptsrc >> pre.txt

echo getting content below the header...
grep -A5000 "<head>" new.html > pro.txt
sed -i 's/<head>//1' pro.txt 

echo merging the two partitions...
cat pro.txt >> pre.txt
cat pre.txt >> new.html

echo opening the website...
start new.html

echo README done.



cd ../
mkdir $1

mv "C:/Users/Mamo/Downloads/README.md" ./
